example1:
	python example1.py dustin

example2:
	python example2.py karl

example2-exc:
	python example2.py jimbo

example3:
	python example3.py http://buildbot.net

example3-exc:
	python example3.py http://hudson.com
